name: CI
on: [push, pull_request]
env:
  DEVELOPER_DIR: /Applications/Xcode_14.2.app/Contents/Developer
jobs:
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: cache-vulkansdk
      id: cache-vulkansdk
      uses: actions/cache@v1
      with:
        path: "VulkanSDK"
        key: VulkanSDK-1.3.239.0-Installer
    - name: vulkansdk
      if: steps.cache-vulkansdk.outputs.cache-hit != 'true'
      run: |
        Invoke-WebRequest -Uri https://sdk.lunarg.com/sdk/download/1.3.239.0/windows/VulkanSDK-1.3.239.0-Installer.exe?Human=true -OutFile VulkanSDK-1.3.239.0-Installer.exe
        7z x -aoa ./VulkanSDK-1.3.239.0-Installer.exe -oVulkanSDK
        Remove-Item .\VulkanSDK\Demos -Recurse
    - name: build
      run: |
        $env:VULKAN_SDK="$(pwd)/VulkanSDK"
        mkdir build; cd build
        cmake -A x64 ../src
        cmake --build . --config Release -j 2

  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: cache-vulkansdk
      id: cache-vulkansdk
      uses: actions/cache@v1
      with:
        path: "1.3.239.0"
        key: vulkansdk-linux-x86_64-1.3.239.0
    - name: vulkansdk
      if: steps.cache-vulkansdk.outputs.cache-hit != 'true'
      run: |
        wget https://sdk.lunarg.com/sdk/download/1.3.239.0/linux/vulkansdk-linux-x86_64-1.3.239.0.tar.gz?Human=true -O vulkansdk-linux-x86_64-1.3.239.0.tar.gz
        tar -xf vulkansdk-linux-x86_64-1.3.239.0.tar.gz
        rm -rf 1.3.239.0/source 1.3.239.0/samples
        find 1.3.239.0 -type f | grep -v -E 'vulkan|glslang' | xargs rm
    - name: build
      run: |
        export VULKAN_SDK=`pwd`/1.3.239.0/x86_64
        mkdir build && cd build
        cmake ../src
        cmake --build . -j 2
        
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: cache-vulkansdk
      id: cache-vulkansdk
      uses: actions/cache@v1
      with:
        path: "vulkansdk-macos-1.3.239.0"
        key: vulkansdk-macos-1.3.239.0
    - name: vulkansdk
      if: steps.cache-vulkansdk.outputs.cache-hit != 'true'
      run: |
        wget https://sdk.lunarg.com/sdk/download/1.3.239.0/mac/vulkansdk-macos-1.3.239.0.dmg?Human=true -O vulkansdk-macos-1.3.239.0.dmg
        hdiutil attach vulkansdk-macos-1.3.239.0.dmg
        sudo /Volumes/vulkansdk-macos-1.3.239.0/InstallVulkan.app/Contents/MacOS/InstallVulkan --root $GITHUB_WORKSPACE/vulkansdk-macos-1.3.239.0 --accept-licenses --default-answer --confirm-command install
        hdiutil detach /Volumes/vulkansdk-macos-1.3.239.0
    - name: build-x86_64
      run: |
        export VULKAN_SDK=$GITHUB_WORKSPACE/vulkansdk-macos-1.3.239.0/macOS
        mkdir build-x86_64 && cd build-x86_64
        cmake -DUSE_STATIC_MOLTENVK=ON -DCMAKE_OSX_ARCHITECTURES="x86_64" \
            -DVulkan_INCLUDE_DIR=$GITHUB_WORKSPACE/vulkansdk-macos-1.3.239.0/MoltenVK/include \
            -DVulkan_LIBRARY=$GITHUB_WORKSPACE/vulkansdk-macos-1.3.239.0/MoltenVK/dylib/macOS/libMoltenVK.dylib \
            -DNCNN_VULKAN=ON -DNCNN_BUILD_TOOLS=OFF -DNCNN_BUILD_EXAMPLES=OFF \
            ../src
        cmake --build . -j 3
    - name: build-arm64
      run: |
        export VULKAN_SDK=$GITHUB_WORKSPACE/vulkansdk-macos-1.3.239.0/macOS
        mkdir build-arm64 && cd build-arm64
        cmake -DUSE_STATIC_MOLTENVK=ON -DCMAKE_OSX_ARCHITECTURES="arm64" \
            -DVulkan_INCLUDE_DIR=$GITHUB_WORKSPACE/vulkansdk-macos-1.3.239.0/MoltenVK/include \
            -DVulkan_LIBRARY=$GITHUB_WORKSPACE/vulkansdk-macos-1.3.239.0/MoltenVK/dylib/macOS/libMoltenVK.dylib \
            -DNCNN_VULKAN=ON -DNCNN_BUILD_TOOLS=OFF -DNCNN_BUILD_EXAMPLES=OFF \
            ../src
        cmake --build . -j 3
