name: macos-x64-gpu
on: [push, pull_request]
jobs:
  macos-clang-gpu:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: cache-vulkansdk
      id: cache-vulkansdk
      uses: actions/cache@v1
      with:
        path: "vulkansdk-macos-1.1.114.0"
        key: vulkansdk-macos-1.1.114.0
    - name: vulkansdk
      if: steps.cache-vulkansdk.outputs.cache-hit != 'true'
      run: |
        wget https://sdk.lunarg.com/sdk/download/1.1.114.0/mac/vulkansdk-macos-1.1.114.0.tar.gz?Human=true -O vulkansdk-macos-1.1.114.0.tar.gz
        tar -xf vulkansdk-macos-1.1.114.0.tar.gz
        rm -rf vulkansdk-macos-1.1.114.0/Applications
        find vulkansdk-macos-1.1.114.0 -type f | grep -v -E 'vulkan|glslang|MoltenVK' | xargs rm
    - name: configure
      run: export VULKAN_SDK=`pwd`/vulkansdk-macos-1.1.114.0/macOS && mkdir build && cd build && cmake -DUSE_STATIC_MOLTENVK=ON -DVulkan_LIBRARY=`pwd`/../vulkansdk-macos-1.1.114.0/MoltenVK/macOS/framework/MoltenVK.framework/MoltenVK ../src
    - name: build
      run: cmake --build build -j 2
    - name: deploy
      run: |
        mkdir realsr-ncnn-vulkan-artifact
        strip build/realsr-ncnn-vulkan
        cp -v build/realsr-ncnn-vulkan realsr-ncnn-vulkan-artifact
        cp -v -r models/* realsr-ncnn-vulkan-artifact
    - uses: actions/upload-artifact@v2
      with:
        name: realsr-ncnn-vulkan-artifact-macos
        path: realsr-ncnn-vulkan-artifact
